# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Barcode', models.IntegerField()),
                ('Branch', models.CharField(max_length=50)),
                ('Year', models.CharField(max_length=10)),
                ('Average_CGPA', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Barcode', models.IntegerField()),
                ('Books_Isued', models.TextField()),
                ('Fine_Due', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Main_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Barcode', models.IntegerField()),
                ('Name', models.CharField(max_length=25)),
                ('Roll_No', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Barcode', models.IntegerField()),
                ('Name', models.CharField(max_length=25)),
                ('Mothers_Name', models.CharField(max_length=25)),
                ('Fathers_Name', models.CharField(max_length=25)),
                ('Address', models.TextField()),
                ('Contact_No', models.IntegerField()),
                ('Email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Semester_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Barcode', models.IntegerField()),
                ('Maths_1', models.CharField(max_length=3)),
                ('Physics_1', models.CharField(max_length=3)),
                ('Basic_Electrical', models.CharField(max_length=3)),
                ('Prog_Fundamentals', models.CharField(max_length=3)),
                ('Engg_Drawing', models.CharField(max_length=3)),
                ('Environment', models.CharField(max_length=3)),
                ('Total_CGPA', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Barcode', models.IntegerField()),
                ('Maths_2', models.CharField(max_length=3)),
                ('Physics_2', models.CharField(max_length=3)),
                ('Chemistry', models.CharField(max_length=3)),
                ('Basic_Mexhanical', models.CharField(max_length=3)),
                ('Workshop_Practice', models.CharField(max_length=3)),
                ('English', models.CharField(max_length=3)),
                ('Total_CGPA', models.FloatField()),
            ],
        ),
    ]
