# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('codewars_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester_2',
            old_name='Basic_Mexhanical',
            new_name='Basic_Mechanical',
        ),
        migrations.AddField(
            model_name='academic_details',
            name='Sem',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='Email',
            field=models.CharField(max_length=50),
        ),
    ]
