# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codewars_api', '0002_auto_20161019_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_details',
            name='Barcode',
            field=models.IntegerField(unique=True),
        ),
    ]
